// lib/main.dart
// Calc-Calories — App Entry Point

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:flutter_secure_storage/flutter_secure_storage.dart';

import 'core/network/api_client.dart';
import 'core/theme/app_theme.dart';
import 'core/theme/app_colors.dart';
import 'core/utils/constants.dart';
import 'features/calorie_tracker/data/models/meal_log_model.dart';
import 'features/calorie_tracker/data/repositories/meal_repository_impl.dart';
import 'features/calorie_tracker/domain/repositories/meal_repository.dart';
import 'features/calorie_tracker/presentation/analyze_meal_screen.dart';
import 'features/calorie_tracker/presentation/bloc/calorie_tracker_bloc.dart';
import 'features/calorie_tracker/presentation/history_screen.dart';

import 'features/auth/data/repositories/auth_repository_impl.dart';
import 'features/auth/domain/repositories/auth_repository.dart';
import 'features/auth/presentation/login_screen.dart';
import 'features/auth/presentation/bloc/auth_bloc.dart';
import 'features/auth/presentation/bloc/auth_event.dart';
import 'features/auth/presentation/bloc/auth_state.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Force portrait orientation
  await SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
    DeviceOrientation.portraitDown,
  ]);

  // Configure status bar for dark theme
  SystemChrome.setSystemUIOverlayStyle(
    const SystemUiOverlayStyle(
      statusBarColor: Colors.transparent,
      statusBarIconBrightness: Brightness.light,
      systemNavigationBarColor: Color(0xFF0D1117),
      systemNavigationBarIconBrightness: Brightness.light,
    ),
  );

  // Initialize Hive
  await Hive.initFlutter();

  // Register Hive adapters (generated by build_runner)
  Hive.registerAdapter(IngredientBreakdownModelAdapter());
  Hive.registerAdapter(MealLogModelAdapter());

  // Open Hive boxes
  await Hive.openBox<MealLogModel>(AppConstants.mealLogsBox);

  runApp(const CalcCaloriesApp());
}

class CalcCaloriesApp extends StatelessWidget {
  const CalcCaloriesApp({super.key});

  @override
  Widget build(BuildContext context) {
    // Wire up dependencies
    final apiClient = ApiClient(
      secureStorage: const FlutterSecureStorage(),
    );
    final MealRepository mealRepository = MealRepositoryImpl(apiClient);
    final AuthRepository authRepository = AuthRepositoryImpl(apiClient);

    return MultiRepositoryProvider(
      providers: [
        RepositoryProvider<MealRepository>.value(value: mealRepository),
        RepositoryProvider<AuthRepository>.value(value: authRepository),
      ],
      child: MultiBlocProvider(
        providers: [
          BlocProvider<AuthBloc>(
            create: (ctx) => AuthBloc(
              authRepository: ctx.read<AuthRepository>(),
            )..add(AppStarted()),
          ),
          BlocProvider<CalorieTrackerBloc>(
            create: (ctx) => CalorieTrackerBloc(
              repository: ctx.read<MealRepository>(),
            ),
          ),
        ],
        child: MaterialApp(
          title: 'Calc Calories',
          debugShowCheckedModeBanner: false,
          theme: AppTheme.darkTheme,
          initialRoute: '/',
          routes: {
            '/': (_) => const AuthWrapper(),
            '/login': (_) => const LoginScreen(),
            '/history': (_) => const HistoryScreen(),
          },
        ),
      ),
    );
  }
}

class AuthWrapper extends StatelessWidget {
  const AuthWrapper({super.key});

  @override
  Widget build(BuildContext context) {
    return BlocBuilder<AuthBloc, AuthState>(
      builder: (context, state) {
        if (state is Authenticated) {
          return const AnalyzeMealScreen();
        }
        if (state is Unauthenticated || state is AuthFailure) {
          return const LoginScreen();
        }
        // Splash / Loading state
        return Scaffold(
          backgroundColor: AppColors.background,
          body: Center(
            child: CircularProgressIndicator(
              valueColor: AlwaysStoppedAnimation<Color>(AppColors.primary),
            ),
          ),
        );
      },
    );
  }
}
